model_repeat_buyer:
  features:
    - weekday_<lambda>
    - hour_median
    - price_sum
    - price_mean
    - payment_type_<lambda>
    - payment_installments_mean
    - payment_value_sum
    - payment_value_mean
    - review_score_mean
    - product_photos_qty_mean
    - delivery_time_mean
    - distinct_product_categories
  target: repeat_buyer
  classify: 1
  test_size: 0.2
  random_state: 42
  n_estimators: 66
  min_samples_split: 3
  min_samples_leaf: 3
  max_features: 8
  max_depth: 6
  learning_rate: 0.25
model_freight_value:
  features:
    - price_mean
    - price_sum
    - geolocation_lat_mean
    - geolocation_lng_mean
    - product_weight_g_mean
    - volume_mean
    - weekday_<lambda>
    - season_<lambda>
    - delivery_time_mean
  target: freight_value_mean
  classify: 0
  test_size: 0.2
  random_state: 42
  loss: 'absolute_error'
  max_depth: 8
  max_features: 7
  min_samples_leaf: 3
  min_samples_split: 2
  n_estimators: 86
  learning_rate: 0.22
model_delivery_time:
  features:
    - weekday_<lambda>
    - hour_median
    - price_mean
    - freight_value_mean
    - product_weight_g_mean
    - customer_city_<lambda>
    - customer_state_<lambda>
    - geolocation_lat_mean
    - geolocation_lng_mean
    - avg_distance_km
  target: delivery_time_mean
  classify: 0
  test_size: 0.2
  random_state: 42
  n_estimators: 50
  min_samples_split: 3
  min_samples_leaf: 2
  max_features: 3
  max_depth: 5
  learning_rate: 0.3
  loss: 'absolute_error'